## Exercise 0

In [1]:
import gpytoolbox as gpy
import polyscope as ps
import numpy as np
import scipy as sp

In [4]:
print(gpy.__version__)
print(ps.np.__version__)
print(np.__version__)
print(sp.__version__)

0.3.2
1.26.4
1.26.4
1.13.1


## Exercise 1

In [8]:
u = np.array([7., 8.])
A = np.array([[1., 2.], [3., 4.], [5., 6.]])
B = np.array([[13., 14.], [15., 16.], [17., 18.]])

print(u)
print(A)
print(B)

print(f'A+B: {A+B}')
print(f'B*A: {B*A}')
print(f'A-3: {A-3}')
print(f'1./A: {1./A}')

[7. 8.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[13. 14.]
 [15. 16.]
 [17. 18.]]
A+B: [[14. 16.]
 [18. 20.]
 [22. 24.]]
B*A: [[ 13.  28.]
 [ 45.  64.]
 [ 85. 108.]]
A-3: [[-2. -1.]
 [ 0.  1.]
 [ 2.  3.]]
1./A: [[1.         0.5       ]
 [0.33333333 0.25      ]
 [0.2        0.16666667]]


### Matrix Arithmetic

In [9]:
print(f'A@u matrix multiplication: {A@u}')
print(f'transpose A.T: {A.T}')
print(f'||A||_F = {np.linalg.norm(A)}')
print(f'||u||= {np.linalg.norm(u)}')

A@u matrix multiplication: [23. 53. 83.]
transpose A.T: [[1. 3. 5.]
 [2. 4. 6.]]
||A||_F = 9.539392014169456
||u||= 10.63014581273465


### Solving Linear Systems

In [11]:
C = np.array([[1., 2.], [3., 4.]])
v = np.array([-2, -3])
print(f'inv(C)@v = {np.linalg.solve(C,v)}')

inv(C)@v = [ 1.  -1.5]


### Sparse Matrices

In [13]:
i = np.array([0,1,1,2])
j = np.array([0,1,2,2])
k = np.array([1., -1., -2., 1.])
D = sp.sparse.csr_matrix((k, (i,j)), shape=(3,3))
w = np.array([-1., 2., 1.])
precomp = sp.sparse.linalg.splu(D)

print(f'inv(D)*b = {sp.sparse.linalg.spsolve(D,w)}')

a = np.array([3., 1., -1.])
print(f"inv(D)*a = {precomp.solve(a)}")
b = np.array([1., 1., -2.])
print(f"inv(D)*b = {precomp.solve(b)}")

inv(D)*b = [-1. -4.  1.]
inv(D)*a = [ 3.  1. -1.]
inv(D)*b = [ 1.  3. -2.]


C:\Users\Rainer Gatzmaga\AppData\Local\Temp\ipykernel_26020\4199561906.py:6: SparseEfficiencyWarning: splu converted its input to CSC format
  precomp = sp.sparse.linalg.splu(D)


## Exercise 2

In [16]:
V = np.array([[0.,0.], [1.,0.], [0.,1.], [1.,1.]])
F = np.array([[0, 1, 2], [2,1,3]])
ps.init()
ps.register_surface_mesh("mesh", V, F)
ps.show()

In [17]:
U,E = gpy.read_mesh('exercise_03/data/penguin.obj')
ps.init()
ps.register_surface_mesh("mesh", U, E)
ps.show()

In [ ]:
gpy.write_mesh("twotriangles.obj", V, F)

In [2]:
VS,FS = gpy.icosphere(5)
ps.init()
ps.register_surface_mesh("sphere", VS, FS)
ps.show()

## Exercise 5

### Boundary Vertices

In [5]:
V,F = gpy.read_mesh("exercise_05/data/penguin_with_bdry.obj")
bl = gpy.boundary_loops(F)
print(f"The boundary has {len(bl)} components.")
ps.init()
ps_penguin = ps.register_surface_mesh("penguin", V, F)
ps_penguin_bdry0 = ps.register_point_cloud("penguin bdry 0", V[bl[0],:])
ps_penguin_bdry1 = ps.register_point_cloud("penguin bdry 1", V[bl[1],:])
ps.show()

The boundary has 2 components.


### Triangle Areas

In [6]:
V,F = gpy.read_mesh("exercise_03/data/penguin.obj")
A = 0.5 * gpy.doublearea(V,F)
print(f"Total mesh area: {np.sum(A)}")
ps.init()
ps_penguin = ps.register_surface_mesh("penguin", V, F)
ps_penguin.add_scalar_quantity("triangle areas", A,
    defined_on='faces', enabled=True)
ps.show()

Total mesh area: 12.730073170563058


### Normals

In [7]:
V,F = gpy.icosphere(2)
N = gpy.per_face_normals(V,F)
ps.init()
ps_sphere = ps.register_surface_mesh("sphere", V, F)
ps_sphere.add_vector_quantity("per face normals", N,
    defined_on='faces', enabled=True)
ps.show()

### Angle Defect

In [8]:
V,F = gpy.read_mesh("exercise_03/data/penguin.obj")
k = gpy.angle_defect(V,F)
ps.init()
ps_penguin = ps.register_surface_mesh("penguin", V, F,
    material='wax', smooth_shade=True)
ps_penguin.add_scalar_quantity("angle defect", k,
    vminmax=(-0.15,0.15), cmap='coolwarm', enabled=True)
ps.show()